version: '3'
services:
  python3:
    container_name: python-3
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ''
    command: sleep inf
    volumes:
    - ./:/usr/src/app
    working_dir: /usr/src/app
